PRODUCT=cbdeps::protoc-gen-go
RELEASE=1.36.11
VERSION=1.36.11
BLD_NUM=53339
PROD_NAME=protoc-gen-go
PRODUCT_PATH=cbdeps/protoc-gen-go
MANIFEST=cbdeps/protoc-gen-go/master.xml
BUILD_JOB=no-op-build
PLATFORMS=
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/couchbase/manifest
TOY_BLD_NUM=53339
PATCH_VIA_GERRIT_OPTS=-r 241344,241354 
