PRODUCT=cbdeps::prometheus
RELEASE=3.11.3
VERSION=3.11.3
BLD_NUM=53483
PROD_NAME=prometheus
PRODUCT_PATH=cbdeps/prometheus
MANIFEST=cbdeps/prometheus/3.11.xml
BUILD_JOB=cbdeps-build
PLATFORMS=linux linux:aarch64 macos macos:arm64 linux:cross-windows
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/ANANTH-SWAMY/manifest
TOY_BLD_NUM=53483
PATCH_VIA_GERRIT_OPTS=
SERVER_RELEASE=totoro
