PRODUCT=couchbase-server
RELEASE=trinity
VERSION=7.6.12
BLD_NUM=53429
PROD_NAME=couchbase-server
PRODUCT_PATH=couchbase-server
MANIFEST=couchbase-server/trinity.xml
BUILD_JOB=couchbase-server-build
PLATFORMS=
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/ANANTH-SWAMY/manifest
TOY_BLD_NUM=53429
PATCH_VIA_GERRIT_OPTS=
