PRODUCT=couchbase-lite-java
RELEASE=4.1.0
VERSION=4.1.0
BLD_NUM=53411
PROD_NAME=couchbase-lite-java
PRODUCT_PATH=couchbase-lite-java
MANIFEST=couchbase-lite-java/4.1.0-toy.xml
BUILD_JOB=couchbase-lite-java
PLATFORMS=
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/couchbaselabs/cblite-manifest
TOY_BLD_NUM=53411
PATCH_VIA_GERRIT_OPTS=
