PRODUCT=cbdeps::erlang
RELEASE=28.3.2
VERSION=28.3.2
BLD_NUM=53400
PROD_NAME=erlang
PRODUCT_PATH=cbdeps/erlang
MANIFEST=cbdeps/erlang/28.3.xml
BUILD_JOB=cbdeps-build
PLATFORMS=linux linux:aarch64 macos macos:arm64 windows_msvc2022
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/couchbase/manifest
TOY_BLD_NUM=53400
PATCH_VIA_GERRIT_OPTS=-r 245091 
SERVER_RELEASE=morpheus
