PRODUCT=rosetta-mcsync
RELEASE=0.7.0
VERSION=0.7.0
BLD_NUM=53525
PROD_NAME=rosetta-mcsync
PRODUCT_PATH=rosetta-mcsync
MANIFEST=rosetta-mcsync/main.xml
BUILD_JOB=rosetta-mcsync-build
PLATFORMS=
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/mhocouchbase/manifest
TOY_BLD_NUM=53525
PATCH_VIA_GERRIT_OPTS=
