PRODUCT=rosetta-mdb
RELEASE=1.0.0
VERSION=1.0.0
BLD_NUM=53505
PROD_NAME=rosetta-mdb
PRODUCT_PATH=rosetta-mdb
MANIFEST=rosetta-mdb/main.xml
BUILD_JOB=rosetta-mdb-build
PLATFORMS=
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/couchbase/manifest
TOY_BLD_NUM=53505
PATCH_VIA_GERRIT_OPTS=-r 251468 
