PRODUCT=couchbase-lite-ios
RELEASE=4.1.3
VERSION=4.1.3
BLD_NUM=53526
PROD_NAME=couchbase-lite-ios
PRODUCT_PATH=couchbase-lite-ios
MANIFEST=couchbase-lite-ios/toy.xml
BUILD_JOB=couchbase-lite-ios-build
PLATFORMS=
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/couchbaselabs/cblite-manifest
TOY_BLD_NUM=53526
PATCH_VIA_GERRIT_OPTS=
