PRODUCT=couchbase-lite-react-native
RELEASE=1.1.0
VERSION=1.1.0
BLD_NUM=53396
PROD_NAME=couchbase-lite-react-native
PRODUCT_PATH=couchbase-lite-react-native
MANIFEST=couchbase-lite-react-native/main.xml
BUILD_JOB=couchbase-lite-react-native-build
PLATFORMS=
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/couchbase/manifest
TOY_BLD_NUM=53396
PATCH_VIA_GERRIT_OPTS=-r 244592 
