PRODUCT=couchbase-lite-android
RELEASE=3.2.5
VERSION=3.2.5
BLD_NUM=53354
PROD_NAME=couchbase-lite-android
PRODUCT_PATH=couchbase-lite-android
MANIFEST=couchbase-lite-android/CBSE-22050-VF.xml
BUILD_JOB=couchbase-lite-android
PLATFORMS=
GO_VERSION=
KEEP_GIT=true
TOY_BUILD=true
MANIFEST_REPO=https://github.com/couchbaselabs/cblite-manifest
TOY_BLD_NUM=53354
PATCH_VIA_GERRIT_OPTS=
